%/////////////////////////////////////////////////
% Research MATLAB code : calculate the magnetic field inside the working bed
% Author: Janaka (856518198)
% Date  : 08/31/2023
%
% Description:
%   This MATLAB code calculate the magnetic field generated by a single 
%   magnet w.r.t it's local coordinate system based on the dipole/complex 
%   model summation model
%
% Inputs:
%   par         : parameters
%   pk          : position vector in local coordinate system (2x1 vector)
% Outputs:
%   hc_field    : magnetic field vector (3x1 vector)
%   hc_norm     : magnetic field norm
%/////////////////////////////////////////////////

function [hc_field,hc_norm]=h_c(par,pk)
    r = pk;
    model = par.model_sel;

    switch model
        case 0 % complex model
            rho = par.rho;
            ak = par.ak_comp;
            r_sub_roh = r - rho;
            r_sub_roh_n = vecnorm(r_sub_roh);
            A_i = r_sub_roh./(r_sub_roh_n.^3);
        case 1 % simple model
            ak = par.ak_dipole;
            m = par.m;
            A_i = (3*m'*r/(vecnorm(r)^5))*r - (m/(vecnorm(r)^3));
        otherwise % default (complex model)
            rho = par.rho;
            ak = par.ak_comp;
            r_sub_roh = r - rho;
            r_sub_roh_n = vecnorm(r_sub_roh);
            A_i = r_sub_roh./(r_sub_roh_n.^3);
    end

    hc_field = A_i*ak;
    hc_norm = norm(hc_field);
end