%/////////////////////////////////////////////////
% Research MATLAB code : calculate the jacobient matrix of the magnetic
% field with respect to position
% Author: Janaka (856518198)
% Date  : 01/21/2026
%
% Description:
%   This MATLAB code calculate the Jacobian matrix of the magnetic field 
%   generated by n magnets in a given location and the given angles of the
%   magnets
%
% Inputs:
%   par         : parameters
%   r           : position vector (2x1 vector)
%   theta_v     : angle vector of magnets (nx1 vector)
% Outputs:
%   H           : Jacobien matrix of the magnetic field (2x2)
%/////////////////////////////////////////////////

function jacobn = Hn(par,r,theta_v)
    phi_rad_k = par.phi_rad;
    rho_k = par.rho_k_rad;
    diff_pos = (r - rho_k');
    jacob_org = zeros(2,2);  % adjust if Hc size known
    
    for i = 1:par.n
        ang = theta_v(i) + phi_rad_k(i);
    
        Ri = R(ang);                     % compute once
        pki = Ri * diff_pos(:,i);        % rotated vector
    
        Hci = Hc(par, pki);              % compute once
    
        jacob_org = jacob_org + Ri.' * Hci * Ri;
    end

    %jacob = sqrt(2 * par.kg)*jacob_org;
    jacobn = sqrt(2*par.kg)*jacob_org;
end