function export_native_reference(runTiming)
%EXPORT_NATIVE_REFERENCE Regenerate native data and tests from __refmod ONLY.
% Generated numerical files use 17 digits to round-trip MATLAB doubles.
if nargin == 0, runTiming = true; end
testDir = fileparts(mfilename('fullpath'));
controlDir = fileparts(testDir);
refDir = fullfile(controlDir,'__refmod');
savedPath = path; savedDir = pwd; savedRng = rng;
cleanup = onCleanup(@() restore(savedPath,savedDir,savedRng)); %#ok<NASGU>
addpath(refDir,'-begin'); cd(refDir);
clear parametersGen R h_c Hc dvecHcdw hn_field Hn gn_field gan_linear
names = {'parametersGen','R','h_c','Hc','dvecHcdw','hn_field','Hn','gn_field','gan_linear'};
for k=1:numel(names)
    assert(strcmpi(fileparts(which(names{k})),refDir),'Wrong reference function: %s',names{k});
end
p = parametersGen();
assert(p.model_sel==0 && p.n==6 && isequal(size(p.rho),[3,144]));
dataDir = fullfile(controlDir,'data');
if ~isfolder(dataDir), mkdir(dataDir); end
fid = fopen(fullfile(dataDir,'ReferenceParameters.h'),'w');
assert(fid>=0,'Cannot write parameter header.');
closer = onCleanup(@() fclose(fid));
fprintf(fid,'// Generated by tests/export_native_reference.m from __refmod.\n');
fprintf(fid,'// All units SI. Do not hand-edit; regenerate from the reference.\n');
fprintf(fid,'#pragma once\n#include "../MagneticModel.h"\nnamespace sixmag::control::detail {\n');
fprintf(fid,'inline ModelParameters referenceParameters() {\n    ModelParameters p;\n');
fields = {'sourceX','sourceY','sourceZ','coefficients','magnetX','magnetY','placementAngles'};
values = {p.rho(1,:),p.rho(2,:),p.rho(3,:),p.ak_comp,p.rho_k_rad(:,1),p.rho_k_rad(:,2),p.phi_rad};
for k=1:numel(fields)
    fprintf(fid,'    p.%s = {\n        ',fields{k});
    v = values{k};
    for j=1:numel(v)
        fprintf(fid,'%.17g',v(j));
        if j<numel(v), fprintf(fid,', '); end
        if mod(j,4)==0 && j<numel(v), fprintf(fid,'\n        '); end
    end
    fprintf(fid,'\n    };\n');
end
fprintf(fid,'    p.kg = %.17g;\n    return p;\n}\n}\n',p.kg);
clear closer
rng(2909,'twister');
azimuth=2*pi*rand(1,512); radius=0.030*sqrt(rand(1,512));
r=[radius.*cos(azimuth); radius.*sin(azimuth)];
th=4*pi*rand(6,512)-2*pi;
r=[r,zeros(2,3)]; th=[th,zeros(6,1),pi*ones(6,1),(pi/2)*ones(6,1)];
for k=0:11
    for angle=[0,pi/2,-pi/2,pi]
        r(:,end+1)=p.a*[cos(k*pi/6);sin(k*pi/6)]; %#ok<AGROW>
        th(:,end+1)=angle*ones(6,1); %#ok<AGROW>
    end
end
fid=fopen(fullfile(testDir,'reference_cases.csv'),'w');
assert(fid>=0,'Cannot write fixtures.');
closer=onCleanup(@() fclose(fid));
fprintf(fid,'# __refmod, model_sel=0; MATLAB %s; seed 2909; SI units\n',version);
fprintf(fid,'# r[2],theta[6],g[2],Gr[4 row-major],Gth[12 row-major],hn[2],Hn[4 row-major]\n');
for k=1:size(r,2)
    g=gn_field(p,r(:,k),th(:,k));
    [Gr,Gth]=gan_linear(p,r(:,k),th(:,k));
    h=hn_field(p,r(:,k),th(:,k)); H=Hn(p,r(:,k),th(:,k));
    row=[r(:,k);th(:,k);g;reshape(Gr.',[],1);reshape(Gth.',[],1);h;reshape(H.',[],1)];
    fprintf(fid,'%.17g,',row(1:end-1)); fprintf(fid,'%.17g\n',row(end));
end
clear closer
fprintf('Exported exact model parameters and %d native reference cases from __refmod.\n',size(r,2));
if runTiming
    samples=zeros(1,7); checksum=0;
    for batch=1:10
        timer=tic;
        for k=1:128
            g=gn_field(p,r(:,k),th(:,k));
            [Gr,Gth]=gan_linear(p,r(:,k),th(:,k));
            checksum=checksum+g(1)+Gr(1)+Gth(1);
        end
        elapsed=toc(timer)/128;
        if batch>3, samples(batch-3)=elapsed; end
    end
    assert(isfinite(checksum));
    fprintf('Reference g+Gr+Gth, median of 7 warmed 128-state batches: %.9f ms/call.\n',median(samples)*1e3);
    fprintf('Reference batch-average range: %.9f to %.9f ms/call.\n',min(samples)*1e3,max(samples)*1e3);
end
end
function restore(p,d,r)
cd(d);path(p);rng(r);
clear parametersGen R h_c Hc dvecHcdw hn_field Hn gn_field gan_linear
end
